# LAB 02.03 - Pandas

<a target="_blank" href="https://colab.research.google.com/github/rramosp/ai4eng.v1/blob/main/content/LAB%2002.03%20-%20PANDAS.ipynb"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!wget --no-cache -O init.py -q https://raw.githubusercontent.com/rramosp/ai4eng.v1/main/content/init.py
import init; init.init(force_download=False); init.get_weblink()

replicating local resources

In [3]:
from local.lib.rlxmoocapi import submit, session
session.LoginSequence(endpoint=init.endpoint, course_id=init.course_id, lab_id="L02.03", varname="student");

logging in as paula.guaring@udea.edu.co... please wait

-------------
using course session ai4eng.v1.udea.r4::2026.1
success!! you are logged in
-------------

In [4]:
import numpy as np
import pandas as pd

## Task 1: Extract data

we have a dataframe of items with a price and, **sometimes**, with an extra column (`margin`).

You will have to complete a function that will **filter** the dataframe selecting the rows:

- whose price is > 100
- **OR** whose margin is >10, if the column `margin` is present

your function must return **A LIST** with the item ids of the selected rows

For instance, with the following dataframe

             price  category
    itemid                  
    56556   108.15       2.0
    73065    83.54       2.0
    36619   114.42       0.0
    73414    82.94       0.0
    13410   115.13       2.0
    66153    91.50       1.0
    77380    85.82       0.0
    73249    95.95       0.0
    11654   100.22       2.0
    11972    77.16       1.0

your must return the following list:

     [56556, 36619, 13410, 11654]
     
But if you get the following dataframe

             price  category  margin
    itemid                          
    39059    98.11       0.0   11.04
    19526    98.11       1.0   11.25
    78176    94.34       1.0   10.51
    50948   102.37       1.0   10.77
    12111    98.07       1.0    8.50
    56191    98.53       1.0   11.65
    38887    91.49       2.0   11.24
    77915   117.30       0.0    8.64
    55010    96.13       0.0    8.95
    45925    98.59       1.0   10.45
    
you must return the following list

    [39059, 19526, 78176, 50948, 56191, 38887, 77915, 45925]

In [5]:
def create_df(missing=False, n=10):
    itemid   = np.random.randint(100000, size=n)+1000
    category = np.random.randint(3, size=n)
    price    = np.round(np.random.normal(loc=100, scale=10, size=n),2)
    margin   = np.round(np.random.normal(loc=10, scale=1, size=n),2)

    if missing:
        nmissing = np.random.randint(len(price)//2)+2
        price[np.random.permutation(len(price))[:nmissing]] = np.nan

    d = pd.DataFrame(np.r_[[price, category, margin]].T, index=itemid, columns=["price", "category", "margin"])
    d.index.name="itemid"
    if np.random.random()>.5:
        d = d[d.columns[:2]]

    return d

In [6]:
d = create_df()
d

         price  category  margin
itemid
83225   103.13       0.0    9.62
33988    92.04       2.0    9.57
71305   117.17       0.0   10.81
65213   107.13       2.0   10.70
30500   104.45       0.0   11.32
40570    91.82       0.0    9.26
42976    81.19       2.0    9.08
26989    98.53       1.0    9.46
63069    94.38       0.0    9.98
33444    92.85       2.0    9.52

In [10]:
def select_items(df):
    # make sure to make a copy in case you modify the original df
    df = df.copy()
    if "margin" in df.columns:
        mask = (df["price"]>100) | (df["margin"]>10)
    else:
        mask = df["price"]>100

    result = list(df[mask].index)

    return result

**manually check your answer**

In [8]:
d = create_df()
d

         price  category  margin
itemid
100696  115.59       2.0   12.34
9987     87.49       2.0    9.53
68343    97.39       0.0    8.59
72009    98.86       2.0   10.21
49233   104.00       0.0    9.25
31777    93.27       0.0    9.45
16697    98.75       1.0   10.25
60258   103.88       1.0   10.35
78251    96.11       1.0    9.81
1566     90.44       0.0    9.67

In [11]:
select_items(d)

[100696, 72009, 49233, 16697, 60258]

**submit your code**

In [12]:
student.submit_task(globals(), task_id="task_01");

## Task 2: Group statistics

Complete the following function so that it returns a dataframe with the average, max and min **prices** per category.

For instance, for the following dataframe

             price  category  margin
    itemid                          
    17946    93.85       1.0   10.64
    61190    91.72       1.0    9.76
    39639   100.16       1.0   10.67
    17791   110.44       2.0    9.65
    7333    101.05       1.0    9.69
    77362   122.33       0.0   11.14
    92646   108.13       2.0   10.58
    27797    85.52       2.0   10.88
    31746    97.56       0.0    9.75
    12355   101.04       2.0    9.51
    
you should return the following dataframe

                 media  maximo  minimo
    categoria                         
    0         109.9450  122.33  97.56
    1          96.6950  101.05  91.72
    2         101.2825  110.44  85.52
    
observe that your result
- must not be a **multilevel** columnset.
- the column names and the index name must be **exactly** as in the example.
- the **index** must be of type **int**.

In [13]:
def get_stats(df):
    df = df.copy()

    result = df.groupby("category")["price"].agg(
        media="mean", maximo="max", minimo="min"
    )
    result.index = result.index.astype(int)
    result.index.name = "categoria"
    return result

**manually check your answer**

In [14]:
d = create_df()
d

         price  category
itemid
92560   101.78       2.0
92559    89.90       2.0
63501    96.31       0.0
81306   103.26       2.0
50620   111.84       1.0
36221    92.57       2.0
26548   101.94       2.0
35454    97.90       0.0
76162   104.04       2.0
52779    95.05       2.0

In [15]:
get_stats(d)

                media  maximo  minimo
categoria
0           97.105000   97.90   96.31
1          111.840000  111.84  111.84
2           98.362857  104.04   89.90

**submit your code**

In [16]:
student.submit_task(globals(), task_id="task_02");

## Task 3: Fill in missing data

Fill in the missing data in the **price** column with the following procedure:

- compute the mean and std of the avaialable prices
- sample from a normal distribution with the computed mean and std (see [`np.random.normal`])(https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html), as many samples as missing data
- substitute the missing values with the samples

For instance, for this input dataframe:

             price  category  margin
    itemid                          
    18922      NaN       1.0   10.32
    69500   121.25       1.0   10.22
    76442    90.25       1.0   12.60
    33863   106.51       0.0   10.26
    15904    95.87       1.0   11.51
    41946   103.47       2.0    9.85
    85451    93.08       2.0    9.56
    70028   116.68       1.0    9.11
    26860      NaN       2.0    9.71
    12807    91.48       0.0    9.77
    
your solution might be similar to this (not exactly the same as you will be sampling data):


                 price  category  margin
    itemid                              
    18922    97.441188       1.0   10.32
    69500   121.250000       1.0   10.22
    76442    90.250000       1.0   12.60
    33863   106.510000       0.0   10.26
    15904    95.870000       1.0   11.51
    41946   103.470000       2.0    9.85
    85451    93.080000       2.0    9.56
    70028   116.680000       1.0    9.11
    26860   103.294843       2.0    9.71
    12807    91.480000       0.0    9.77
    
    
**WARN**: your function must not modify the original dataframe, make a copy of the input dataframe, fill the values in the copy and return it.

**HINT**: use the [`isna()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.isna.html) method of a dataframe or a series.

In [17]:
d = create_df(missing=True)
d

         price  category
itemid
21190      NaN       2.0
27867    79.10       2.0
14316      NaN       0.0
88890   110.71       1.0
4475       NaN       2.0
14893   108.98       0.0
58334      NaN       1.0
13120      NaN       1.0
62444   106.31       1.0
64102   103.58       0.0

In [18]:
def fillna(df):
    df = df.copy()

    mean = df["price"].mean()
    std = df["price"].std()
    missing = df["price"].isna().sum()

    df.loc[df["price"].isna(), "price"] = np.random.normal(mean, std, missing)


    result = df
    return result

**check manually your code**

In [19]:
d = create_df(missing=True)
d

         price  category
itemid
24181   106.95       0.0
69469    96.04       1.0
3218       NaN       1.0
67356    99.16       2.0
57321   109.28       0.0
10236    99.34       1.0
52937      NaN       0.0
27512    87.04       2.0
63710      NaN       0.0
48345      NaN       0.0

In [20]:
fillna(d)

             price  category
itemid
24181   106.950000       0.0
69469    96.040000       1.0
3218     96.001743       1.0
67356    99.160000       2.0
57321   109.280000       0.0
10236    99.340000       1.0
52937    97.992642       0.0
27512    87.040000       2.0
63710    94.338097       0.0
48345   101.158691       0.0

**submit your code**

In [21]:
student.submit_task(globals(), task_id="task_03");